# Generated by Django 5.2.6 on 2025-09-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='publication_date',
        ),
    ]
